### ISSUE TITLE
Tutorial/Example

### ISSUE THREAD

**Issue by zwells0225** [itavero/flutter-ble-uart#1]
Hi Arno,

Gentile reminder regarding a tutorial and/or example app.

**Comment by zwells0225** [comment]
Another example by sonny can be found here:
http://sayaw.net/main_dart.txt

**Comment by itavero** [comment]
I'll see if a can find some time to clean up my own test application and include it in the repository.
Unfortunately you've caught me at a bad time (both at work and at home I'm getting ready to move, so I'm pretty busy the coming month or so).

**Comment by itavero** [comment]
@zwells0225 I know it's not a full example yet, but I added a few lines of code in a Markdown file.
Hopefully this is enough to get you started.

See `example/README.md` ([click](https://github.com/itavero/flutter-ble-uart/tree/master/example)).

**Comment by zwells0225** [comment]
Thank You very much!  The ReadMe is much appreciated.  I'll give it a go this week.
