### ISSUE TITLE
Version solving failed

### ISSUE THREAD

**Issue by frey1esm** [itavero/flutter-ble-uart#2]
`Because my_app depends on flutter_ble_uart from git which depends on flutter_blue ^0.4.0, flutter_blue ^0.4.0 is required.
So, because my_app depends on flutter_blue ^0.6.0+1, version solving failed.`

**Comment by itavero** [comment]
Thank you for creating the issue. Just out of curiosity, is there any specific reason you cannot have your app depend on the older version?
If you are not using it for anything else, I don't think you actually need to depend on flutter_blue directly.

As mentioned in my email, I'll try to see if it's an easy change to update flutter_blue, but I'm afraid this won't be the case as their change log mentions multiple breaking changes.

**Comment by frey1esm** [comment]
I had issues with device scanning in flutter_blue 0.4.0, which doesn’t currently work with my flutter app code.


But, I will remove my direct dependency and see how far I get with your current code….will report back. Thanks!


 






  
  Sincerely,


David Frey
ESM, LLC
513.677.1880 office
513.256.1080 mobile
dfrey@1esm.com

**Comment by itavero** [comment]
Okay, that sounds like a good reason to want to use the newer version ;)

Looking at my schedule, I might be able to free up some time next weekend to have a quick look. No promises, though!

**Comment by frey1esm** [comment]
Thanks!




  
  Sincerely,


David Frey
ESM, LLC
513.677.1880 office
513.256.1080 mobile
dfrey@1esm.com

**Comment by frey1esm** [comment]
Update:  Got my flutter app talking to my Feather with your library and flutter_blue 0.4.0

**Comment by zwells** [comment]
I did as well! Thanks @itavero

**Comment by itavero** [comment]
Great! Let's keep this issue open so I don't forget to check if an update is possible anyway 👍

**Comment by frey1esm** [comment]
> Great! Let's keep this issue open so I don't forget to check if an update is possible anyway 👍
Yes...you'll need ^0.6.0+1 for the changes/fixes to scan/stop scan, connect/disconnect functionality, from what I can see. There are a [few issues](https://github.com/pauldemarco/flutter_blue/issues/19) in the flutter-blue repo.

**Comment by frey1esm** [comment]
Biggest issue for me on 0.4.0 is not being able to properly disconnect bluetooth. You can disconnect the Serial stream but not the connection itself.

**Comment by zwells** [comment]
@frey1esm You may want to have a look at Brad Hacker's project.  He implements 0.5.0 and everything is done in the main.dart 

His findUART() function for the device list helped me out a lot.

https://github.com/BradHacker/cycler-controller
